wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696964852.783706
    t:
      1:
      - 1
      - 5
      - 33
      - 35
      - 53
      - 55
      3:
      - 23
      4: 3.11.0
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
